apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: visionesoft-ingress
  namespace: visionesoft
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.visionesoft.com
        - admin.visionesoft.com
      secretName: visionesoft-tls
  rules:
    - host: api.visionesoft.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 80
    - host: admin.visionesoft.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backoffice
                port:
                  number: 80
